//! Build-time codegen: parses [`CONSTANTS_PATH`] and emits a matching TypeScript module at [`OUT_PATH`] so the frontend (board.svelte, shaders) can consume the same numeric constants without duplicating their literal values.

use std::env;
use std::fs;
use std::path::PathBuf;

const CONSTANTS_PATH: &str = "src/shared_constants.rs";
const OUT_PATH: &str = "src/lib/generated/shared-constants.ts";

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let src = manifest_dir.join(CONSTANTS_PATH);
    println!("cargo:rerun-if-changed={}", src.display());
    println!("cargo:rerun-if-changed=build.rs");

    let contents = fs::read_to_string(&src)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", src.display()));

    // Parse `pub const NAME: f64 = <number>;` lines.
    let mut entries: Vec<(String, String)> = Vec::new();
    for raw_line in contents.lines() {
        let line = raw_line.trim();
        let Some(rest) = line.strip_prefix("pub const ") else {
            continue;
        };
        let Some((name, after)) = rest.split_once(':') else {
            continue;
        };
        // Expect ` f64 = <value>;`
        let Some(eq_idx) = after.find('=') else {
            continue;
        };
        let value_part = after[eq_idx + 1..].trim();
        let value = value_part.trim_end_matches(';').trim();
        entries.push((name.trim().to_string(), value.to_string()));
    }

    if entries.is_empty() {
        panic!(
            "shared_constants.rs contained no `pub const` declarations; check the file format expected by build.rs"
        );
    }

    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("expected build.rs to live at <workspace>/crates/game/build.rs");
    let out_path = workspace_root.join(OUT_PATH);

    let mut ts = String::new();
    ts.push_str("// AUTO-GENERATED by crates/game/build.rs from\n");
    ts.push_str(format!("// crates/game/{}.\n", CONSTANTS_PATH).as_str());
    ts.push_str("// Edit that file, not this one.\n\n");
    for (name, value) in &entries {
        ts.push_str(&format!("export const {name} = {value};\n"));
    }

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)
            .unwrap_or_else(|e| panic!("failed to create {}: {e}", parent.display()));
    }

    // Only rewrite if the contents changed.
    let needs_write = match fs::read_to_string(&out_path) {
        Ok(existing) => existing != ts,
        Err(_) => true,
    };
    if needs_write {
        fs::write(&out_path, ts)
            .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
    }
}
